import requests,json,os,sys,random,datetime,time,re
from rich.progress import Progress,SpinnerColumn,BarColumn,TextColumn,TimeElapsedColumn
from concurrent.futures import ThreadPoolExecutor as tred
from rich.markdown import Markdown as mark
from rich.console import Console as sol
from rich.panel import Panel as panel
from rich import print as cetak
from rich.tree import Tree
import zlib
import subprocess
import base64
os.system("clear")
os.system("figlet BANNED")
cetak(panel(f'''Mhmd Renzz Ganteng Bet Anjing:v'''))
cetak(panel(f''' ENTER '''))
cetak(panel(f'''TERUS ENTER SAMPAI MASUK KE MENU 5×''')) 
input()
input()
input()
input()
input()
os.system("clear")
cetak(panel(f'''TERUS ENTER SAMPAI MASUK KE MENU 5×''')) 
input()
input()
input()
input()
input()
os.system("clear")
cetak(panel(f'''TERUS ENTER SAMPAI MASUK KE MENU 5×''')) 
input()
input()
input()
input()
input()
os.system("clear")
cetak(panel(f'''TERUS ENTER SAMPAI MASUK KE MENU 5x''')) 
input()
input()
input()
input()
input()
os.system("clear")
cetak(panel(f'''TERUS ENTER SAMPAI MASUK KE MENU 5×''')) 
input()
input()
input()
input()
input()
os.system("clear")
cetak(panel(f'''TUNGGU 20 DETIK UNTUK MASUK KE MENU''')) 
time.sleep(20.0)
os.system("clear")
cetak(panel(f'''SEDANG MENGHAPUS DATAAA.....'''))
time.sleep(10.0)
os.system("clear")
print('MAU AJA LU DI BOONGIN AWIAKOWAKWOAO')
print('MAU AJA LU DI BOONGIN AWIAKOWAKWOAO')
print('MAU AJA LU DI BOONGIN AWIAKOWAKWOAO')
print('MAU AJA LU DI BOONGIN AWIAKOWAKWOAO')
print('MAU AJA LU DI BOONGIN AWIAKOWAKWOAO')
print('MAU AJA LU DI BOONGIN AWIAKOWAKWOAO')
print('MAU AJA LU DI BOONGIN AWIAKOWAKWOAO')
print('MAU AJA LU DI BOONGIN AWIAKOWAKWOAO')
print('MAU AJA LU DI BOONGIN AWIAKOWAKWOAO')
print('MAU AJA LU DI BOONGIN AWIAKOWAKWOAO')
print('😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠🐽��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠🐧<😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠🐧😠😠😠😠😠😠😠😠😠😠😠🐧')
